### ISSUE TITLE
What about JSON Activity Streams?

### ISSUE THREAD

**Issue by lmorchard** [brentsimmons/JSONFeed#20]
If the main thing here is JSON, then why not use [Activity Streams](https://www.w3.org/TR/activitystreams-core/)? That JSON-based spec covers some semantics that describe new things we've done with social media since the era of title/date/link/content blog feed.

If anything, consider this a FAQ/doco request. Would like to see it as a right-tool-for-the-job scenario and not a new RSS-vs-Atom scenario.

**Comment by pfefferle** [comment]
...and there is also a relatively widely adopted, direct rss to json mapping from @scripting (Dave Winer)

* http://scripting.com/stories/2012/09/10/rssInJsonForReal.html

**Comment by scripting** [comment]
It *wasn't* widely adopted. It mostly went pffft, no interest as far as I can tell.

**Comment by pfefferle** [comment]
there was at least a discussion to make it the main WordPress json feed: https://core.trac.wordpress.org/ticket/25639

**Comment by scripting** [comment]
Thanks for the pointer. I didn't know that they discussed it.

I had forgotten about rssjs.org. Fortunately it's preserved in archive.org.

https://web.archive.org/web/20130325100705/http://rssjs.org:80/

Dave

**Comment by gruber** [comment]
I would argue that Activity Streams is very different from JSON Feed, insofar as it is, to my eyes, not simple at all. JSON Feed is very simple -- I'll be most people could learn it just by looking at examples. JSON Feed is therefore way more limited, but that's the tradeoff for something so simple that it's self-describing.

I am reminded of when I shipped Markdown, and people would ask why not use (to name one example) [reStructuredText](http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html) instead? reStructuredText has more features and is more powerful. Markdown, though, is far simpler. Sometimes simplicity wins.

**Comment by lmorchard** [comment]
> Sometimes simplicity wins.

And that's a fine reason, IMO... it de facto won a lot of arguments during the angst about XML vs RDF vs whatever back in the early 2000s

**Comment by ttepasse** [comment]
Activity Streams were originally an extensions for Atom Feeds. Then they morphed into the linked data initiative. Yes, it's not simple, mostly, because they want to to more complicated things, like syndicating more than just blog posts but the social actions we use on modern social networks. In a way the fight between "simple/stable" and "more interesting things" is a description of the fights between the feed format wars and all the different modern initiatives trying a distributed social web. RSS 0.9 had RDF, then it got simplified, then it got reimagined with RDF as RSS 1.0 because people saw a need, then RSS 2.0 responded with some namespace support. Etcetera. 

My point is: There will always be this need for something more complicated (which is a loaded word, yes). Activitystreams seem to be the technique behind OStatus/GNU Social. Which is only one part of our wonderful new fragmented world, there is the Indieweb movement with h-feed and complicated Microformats doing the same thing, there were Diaspora, Tent and multiple others. And you could think of RDFa, Microdata and schema.org in the same realm. And now there's a new fragmentation with JSON Feeds for simplicity.

A FAQ item about the relations or non-relations to other initiatives in this realm would be interesting.

**Comment by strugee** [comment]
@ttepasse https://w3c-social.github.io/social-web-protocols/ may cover a lot of what you're looking for.

Full disclosure, I'm a member of the W3C SocialWG working on this stuff, but a lot of what ActivityStreams is trying to do is simplify OStatus. I think it finds a good balance - it's very expressive but everything can be expressed simply, in one protocol. Instead of complexly with lots of protocols (OStatus). The IndieWeb and microformats2 are also very, very simple, and have stood the test of time - Google, for example, has replaced their "preferred" semantic markup system several times since they kept inventing new stuff, but continued to parse mf2 the entire time. At least IIRC. I used to have a reference for this but have since lost it; I'll ask the mf2 editor.

**Comment by strugee** [comment]
Not from who I thought it was from, but here's what I was thinking of: https://aaronparecki.com/2016/12/17/8/owning-my-reviews

**Comment by scripting** [comment]
It turns out WordPress did/does support rss.js.

http://scripting.com/2013/12/14/wordpressSupportsRssjs.html

I was doing a little research and came across this post.

Good think I blog, cause my memory is so bad. ;-)

**Comment by scripting** [comment]
One more thing -- there was/is a microblog namespace. 

http://microblog.reallysimple.org/

Dave

**Comment by scripting** [comment]
BTW, re http://rssjs.org/ -- I re-registered the name and rescued the content from archive.org.

Also, Disqus preserved the comments, and there was quite a bit of interesting stuff there.

I had almost completely forgotten it. 

Dave

**Comment by manton** [comment]
Good discussion here, thanks everyone. Activity Streams is a different thing. It's still valuable to have something simple like JSON Feed that can be implemented anywhere.
