### ISSUE TITLE
Items with summary but without content_*

### ISSUE THREAD

**Issue by valtlai** [brentsimmons/JSONFeed#27]
There are feeds whose items don’t have real content but a short summary. In my opinion, it would be more appropriate to use `summary` instead of `content_text` or `content_html` in those cases.

**Comment by manton** [comment]
It's okay to use `content_text` even if the text there isn't a complete representation of the item. It can be used like a summary or excerpt if that's all you have. I think it's important that clients can rely on either `content_text` or `content_html` being there.

**Comment by mryellow** [comment]
> content_html and content_text are each optional strings — but one or both must be present.

These should both be optional parameters.

The use-case is doing low-bandwidth feeds of headlines, rather than *"download the entire site in one handy file"*.

**Comment by mryellow** [comment]
Slept on it, have a few examples:

* I have a page which displays short excerpts of the stories.
* I'm very likely to use the `summary` parameter.
* Client-side: Given `summary` is optional I can't rely on it being specified.
* Server-side: I have to send exactly the same data in both `summary` and `content_text` fields as `content_*` is required.

Okay so lets say I use `content_text` as my except instead and leave `summary` blank. That will work fine for my site where I know `content_text` is only a summary and `summary` can be ignored.

What happens when I use another feed, they've included the whole article in `content_text`. Meaning I can't use `content_text` as an excerpt anymore and instead must use `summary`, at which point I have to include the same data in both fields again.

If anything the *least* amount of information should be required and the *expansion* of that into a full article be optional.

**Comment by manton** [comment]
Just catching up and closing this out. JSON Feed is more like RSS than Atom in how it thinks about `summary`. In my experience, `summary` isn't used very often… It adds complexity if clients have to check `summary` in addition to the 2 flavors of `content_` fields.
