### ISSUE TITLE
Use a better format for responsive images

### ISSUE THREAD

**Issue by domenic** [brentsimmons/JSONFeed#4]
Instead of using differently-named keys like "icon" and "favicon", use a single key with a more flexible way of specifying image sizes. This has precedent in [web app manifests](https://w3c.github.io/manifest/); see the [example manifests](https://w3c.github.io/manifest/#example-manifests) to get a look at it in action.

**Comment by donohoe** [comment]
I would recommend an approach that describes Aspect Ratio and the general Size. Across multiple media orgs I've worked at this has proved consistently helpful.

You can include further info with specific width and height within that.

For example:

```
"images": {
	"16x9_1x" : {
		"id": "1",
		"content_text": "Whatever",
		"url": "http://ww2.qa1.hdnux.com/photos/51/51/41/10917985/4/sub_section_content.jpg"
	},
	"16x9_2x" : {
		"id": "2",
		"content_text": "Whatever",
		"url": "http://ww2.qa1.hdnux.com/photos/51/51/41/10917985/4/landscape_169.jpg"
	},
	"16x9_3x" : {
		"id": "3",
		"content_text": "Whatever",
		"url": "http://ww2.qa1.hdnux.com/photos/51/51/41/10917985/4/mobile_landscape.jpg"
	},
	"3x2_1x" : {
		"id": "4",
		"content_text": "Whatever",
		"url": "http://ww2.qa1.hdnux.com/photos/51/51/41/10917985/4/river_premium_exclusive.jpg"
	},
	"3x2_2x" : {
		"id": "5",
		"content_text": "Whatever",
		"url": "http://ww2.qa1.hdnux.com/photos/51/51/41/10917985/4/landscape_large.jpg"
	},
	/* ... and so on ... */
}

```

**Comment by domenic** [comment]
My hope was that you could just reuse the web app manifest format, as it's being used consistently across all web specs, and will become familiar to web developers.

**Comment by donohoe** [comment]
You could, but its not at all helpful in my experience. Sorry if I sound overly opinionated in this - not intentional!

The issue with web app manifest spec is that you then have to cut specific images of specific image sizes. 

When your content could be consumed by web, Apple TV, random app, Chrome extension, each might have its own specific image sizes and minor variations that mean creating yet another image... its not the best approach and it has burned a lot of publishers.

Last time I checked, The New York Times feeds included almost 50 images of various specific sizes to support minor differences across platforms. Aspect ratios would have avoided much of that overhead.

**Comment by domenic** [comment]
I don't really understand. You can compute the aspect ratio from the size. The platform then decides which is the best combination of aspect ratio + size appropriate for the display surface.

An aspect-ratio-only format contains strictly less information than one with the size information.

**Comment by donohoe** [comment]
You can always compute anything given the info. You can always use XML instead of JSON too, yet here is this project 😃 

I'm saying, from a practical development perspective:

1. You should have to compute if its avoidable
2. Web app manifest as it stands encourages inefficient behaviors on the backend

**Comment by domenic** [comment]
I disagree with (2), and in practice I think computing the aspect ratio of 1.777... repeating is just as easy from the string "240x135" as it is from "16x9".

**Comment by donohoe** [comment]
The question is, if your target audience here actual publishers?

If not, then fine. I'll take it back.

If yes, then don't be so quick to dismiss (2). Its not a matter of opinion. I've been witnessing this issue and dealing with it with a lot of publishers. I'm talking NYTimes, Quartz/Atlantic Media, The New Yorker/Conde Nast, Hearst (SF Chronicle, Houston Chronicle, SFGate, Times Union, MySA, SeattlePI etc...).

Even if my suggestions is not the best solution, at the very least, the web app manifest is a pain and was poorly thought out.

**Comment by st3fan** [comment]
Don't forget about SVG please. A lot of images are being replaced by SVG or even PDF. Does this need a `media_type`? It is not a good idea to let clients guess from the filename.

**Comment by donohoe** [comment]
@st3fan The filename extension is as explicit as you get, no?

**Comment by darobin** [comment]
Not all systems support arbitrary filename extensions. URLs are supposed to be meaningless (and have no notion of file extension whatsoever) and some systems take that for granted. I know of systems in which every asset is stored as a UUID, if the decision is supposed to be made on file extension then it would break there.

Some clients don't support SVG (because of embedded scripting), some clients don't support WebP. Allowing them to make a media-type-based decision as to what to fetch would be pretty useful.

**Comment by donohoe** [comment]
Not to get into the weeds, but URLs are not meant to be meaningless and do have a notion of filename and extension. The path aspect of the URL was based on mapping file system path - though its not bound by hierarchy.

That said (and even if we don't agree), adding something akin to media-type is (to me anyway) a more heavy-handed approach than relying on filename extension which would be present/used in most cases.

I think this loops back to what the scope of the spec is. If its just intended as a basic RSS alternative then maybe we should dig too deep. However if it was ambitions to be used by publications and media orgs in the course of their work, then yeah, we should dig into this more.

**Comment by darobin** [comment]
I don't want to go deep into this, and I have strong reservations about whether it was the correct architectural choice, but [AWWW](https://www.w3.org/TR/webarch/#uri-opacity) is extremely explicit about URL opacity, as is [RFC3986](https://tools.ietf.org/html/rfc3986#section-3.3), [URL](https://url.spec.whatwg.org/) is pretty much syntax-only (by design AFAIK), and [MIME Sniffing](https://mimesniff.spec.whatwg.org/#interpreting-the-resource-metadata) explicitly rules out using the file extension as unreliable. I don't want to make an argument "by law" but I would say that anything that somehow magically manages to put the W3C, the IETF, and the WHATWG on the exact same page ought to be taken extremely seriously ;-)

To your other point, I think there may be a middle way between just a straight port of RSS and a feature-creepy monster which is to think of JSON feed as RSS if RSS had been initially designed today. We know a lot more about some aspects of publishing today than we did in those halcyon times of web-safe bgcolors. I'm not sure how extensive the additional feature set you would have in mind for media orgs, but that might already cover a fair bit of ground? I reckon it depends on how extensive you would plan it to be — speaking for us (science publishing), if it's just for updates about the latest articles in a journal then we'd be fine with something like that (if however the goal would be to be able to transmit full articles such that they can be republished, we'd need a _lot_ more information).

**Comment by ttepasse** [comment]
I don't want to overcomplicate it, but there is also a difference of resolution switching. There is a reason why the HTML and CSS syntaxes for [responsive images](https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images) are somewhat complex. I don't know if a feed specification should mirror that. Also the existing syntaxes don't mirror well into JSONs hierarchical nature. But I think if, then srcset syntax should be more familiar for web developers than web app manifests.

**Comment by st3fan** [comment]
@donohoe URLs are not meaningless, but they say nothing about content types. If you want to know the content type of something that is being served, look at the content-type header, or if the source reference supports it, provide the type beforehand.

I have a server that produces `/feed/1234/icon` - what do we make of that?

**Comment by manton** [comment]
Thanks y'all. I think it's too much to add this to the spec… Best to have a very simple solution in the spec that works for a lot of apps, and if feed readers really need more options they can check the source HTML, which might contain images at other resolutions.
